FROM centos:centos7
MAINTAINER Roland Kammerer <roland.kammerer@linbit.com>

ENV DRBD_VERSION 9.0.19-1

RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical && \
	yum install -y wget gcc make && yum clean all -y

RUN wget https://www.linbit.com/downloads/drbd/9.0/drbd-${DRBD_VERSION}.tar.gz -O /drbd.tar.gz && \
    wget https://raw.githubusercontent.com/LINBIT/drbd/drbd-9.0/docker/entry.sh -O /entry.sh

RUN chmod +x /entry.sh
ENTRYPOINT /entry.sh
