#@ load("funcs.lib.yml", "map_host_linstor", "map_host_lvm", "name", "namespace", "timezone", "node", "initimage", "controllerhostport", "registry", "controllerimage", "satelliteimage", "set_priority_class")
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ node()
  namespace: #@ namespace()
data:
  INIT_DEBUG: 'false'
  #! Must be an FQDN here, otherwise it might not resolve!
  LS_CONTROLLERS: #@ controllerhostport()
  POOL_BASE_DIR: #@ "/var/lib/" + name() + "/storagepools"
  DRBD_IMG_REPO: quay.io/piraeusdatastore
  DRBD_IMG_TAG: v9.0.22 #! "none" will skip drbd installation
  DRBD_IMG_PULL_POLICY: IfNotPresent
  MAP_HOST_LVM: 'true'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: #@ node()
  namespace: #@ namespace()
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name()
      app.kubernetes.io/component: #@ node()
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name()
        app.kubernetes.io/component: #@ node()
    spec:
      #@ if set_priority_class():
      priorityClassName: system-node-critical
      #@ end
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: init
        image: #@ initimage()
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          #! requests:
          #!   cpu: 100m
          #!   memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name:  #@ node()
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
            - initNode
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
        - name: #@ "opt-" + name()
          mountPath: #@ "/opt/" + name()
        - name: drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
      containers:
      - name: satellite
        image: #@ satelliteimage()
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          #! requests:
          #!   cpu: '100m'
          #!   memory: '200Mi'
          limits:
            cpu: 300m
            memory: 300Mi
        envFrom:
        - configMapRef:
            name:  #@ node()
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #@ if name() == "piraeus":
        args:
        - startSatellite
        #! - --stack-traces
        #! - --log-level
        #! - TRACE
        #@ end
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          tcpSocket:
            port: 3366
          periodSeconds: 5
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: init
          mountPath: /usr/bin/pre-start.sh
          subPath: bin/prestart-node.sh
        - name: log
          mountPath: /var/log/linstor-satellite
        - name: #@ "var-lib-" + name()
          mountPath: #@ "/var/lib/" + name()
        #! - name: default-storage-pool
        #!   mountPath: /DfltStorPool
        - name: dev
          mountPath: /dev
        - name: lib-modules
          mountPath: /lib/modules
        #@ if map_host_lvm():
        - name: run-lvm
          mountPath: /run/lvm
        - name: run-udev
          mountPath: /run/udev
        #@ end
        #@ if map_host_linstor():
        - name: var-lib-linstor-d
          mountPath: /var/lib/linstor.d
        #@ end
      volumes:
      - name: timezone
        hostPath:
          path: #@ timezone()
      - name: init
        emptyDir: {}
      - name: #@ "opt-" + name()
        hostPath:
          path: #@ "/opt/" + name()
      - name: #@ "var-lib-" + name()
        hostPath:
          path: #@ "/var/lib/" + name()
      #! - name: default-storage-pool
      #!   hostPath:
      #!     path: /DfltStorPool
      - name: log
        hostPath:
          path: #@ "/var/log/"+ name() + "/linstor-satellite"
      - name: dev
        hostPath:
          path: /dev
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
      #@ if map_host_lvm():
      - name: run-lvm
        hostPath:
          path: /run/lvm
      - name: run-udev
        hostPath:
          path: /run/udev
      #@ end
      #@ if map_host_linstor():
      - name: var-lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: etc-linstor
        hostPath:
          path: /etc/linstor
      #@ end
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: #@ name() + "/node"
                operator: In
                values:
                  - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      #! imagePullSecrets:
      #! - name: piraeus-regcred
