#@ load("funcs.lib.yml", "map_host_linstor", "map_host_lvm", "name", "namespace", "timezone", "node", "initimage", "controllerhostport", "registry", "controllerimage", "satelliteimage", "clientimage", "set_priority_class")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ name() + "-scaler"
  namespace: #@ namespace()
data:
  INIT_DEBUG: 'false'
  #! Must be an FQDN here, otherwise it might not resolve!
  LS_CONTROLLERS: #@ controllerhostport()
  POOL_BASE_DIR: #@ "/var/lib/" + name() + "/storagepools"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ name() + "-scaler-task"
  namespace: #@ namespace()
data:
  task: "" #! placeholder
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: #@ name() + "-scaler"
  namespace: #@ namespace()
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name()
      app.kubernetes.io/component: #@ name() + "-scaler"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name()
        app.kubernetes.io/component: #@ name() + "-scaler"
    spec:
      #@ if set_priority_class():
      priorityClassName: system-node-critical
      #@ end
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - name: init
        image: #@ initimage()
        imagePullPolicy: IfNotPresent
        resources:
          #! requests:
          #!   cpu: 50m
          #!   memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name:  #@ name() + "-scaler"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
          - initScaler
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
      containers:
      - name: scaler
        image: #@ clientimage()
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          #! requests:
          #!   cpu: 100m
          #!   memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name:  #@ name() + "-scaler"
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
          - /init/bin/run-scaler.sh
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: run
          mountPath: /var/run/task
          subPath: task
        - name: #@ "var-lib-" + name()
          mountPath: #@ "/var/lib/" + name()
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
      volumes:
      - name: timezone
        hostPath:
          path: #@ timezone()
      - name: init
        emptyDir: {}
      - name: run
        configMap:
          name: #@ name() + "-scaler-task"
          items:
          - key: task
            path: task
            mode: 0755
      - name: #@ "var-lib-" + name()
        hostPath:
          path: #@ "/var/lib/" + name()
      - name: dev
        hostPath:
          path: /dev
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: #@ name() + "/node"
                operator: In
                values:
                  - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      #! imagePullSecrets:
      #! - name: piraeus-regcred
