#@ load("funcs.lib.yml", "name")
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-local-dflt-r1"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-local-dflt-r2"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-local-dflt-r3"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "3"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-local-dflt-raw"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-dflt-r1"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "1"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-dflt-r2"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-dflt-r3"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "3"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-dflt-raw"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: DfltStorPool
