FROM centos:centos7
MAINTAINER Roland Kammerer <roland.kammerer@linbit.com>

RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical && \
	yum install -y gcc make patch diffutils perl kmod && yum clean all -y

ARG DRBD_VERSION
ADD https://pkg.linbit.com/downloads/drbd/9/drbd-${DRBD_VERSION}.tar.gz /drbd.tar.gz
ADD --chmod=0755 https://raw.githubusercontent.com/LINBIT/drbd/master/docker/entry.sh /entry.sh

ENV LB_HOW compile
ENTRYPOINT /entry.sh
