FROM debian:buster

RUN apt-get update && apt-get upgrade -y && apt-get install -y kmod gnupg make gcc patch diffutils perl elfutils curl 'linux-kbuild-*' && apt-get clean

ARG DRBD_VERSION
ADD https://pkg.linbit.com/downloads/drbd/9/drbd-${DRBD_VERSION}.tar.gz /drbd.tar.gz
ADD --chmod=0755 https://raw.githubusercontent.com/LINBIT/drbd/master/docker/entry.sh /entry.sh

ENV LB_HOW compile
ENTRYPOINT /entry.sh
