FROM almalinux:10
MAINTAINER Roland Kammerer <roland.kammerer@linbit.com>

RUN dnf -y update-minimal --security --sec-severity=Important --sec-severity=Critical && \
	dnf install -y gcc make patch diffutils perl elfutils-libelf-devel kmod && dnf clean all -y

ARG DRBD_VERSION
ADD https://pkg.linbit.com/downloads/drbd/9/drbd-${DRBD_VERSION}.tar.gz /drbd.tar.gz
ADD --chmod=0755 https://raw.githubusercontent.com/LINBIT/drbd/master/docker/entry.sh /entry.sh

ENV LB_HOW compile
ENTRYPOINT /entry.sh
